### PR TITLE
Add test and docs for nested block directives

### PR DESCRIPTION
**Pull request by raboof**
Refs #185

### CODE REVIEW

**Comment by 2m** [comment]
Does it work because of the additional `@`? If so, I think we should mention that explicitly in the docs.

**Comment by raboof** [comment]
Yes that's what helps it match correctly

**Comment by raboof** [comment]
done

**Comment by 2m** [comment]
Awesome pawsome! :feet:

**Comment by pvlugter** [comment]
👍 thanks for documenting

**Pull request merged**
