### PR TITLE
sbt-web 1.5.3 (was 1.4.4)

### PR DESCRIPTION
**Pull request by mkurz**
Replaces

- #592

fixes compiler errors

### CODE REVIEW

**Comment by mkurz** [comment]
@johanandren Can you approve the workflows? Thanks!

**Comment by mkurz** [comment]
Also the reason this should be merge asap is because sbt-web 1.4.4 is still hosted on https://repo.scala-sbt.org/ whereas 1.5x+ are hosted on maven central (important in the light of https://github.com/sbt/sbt/issues/7202)

**Comment by mkurz** [comment]
@johanandren Green! Can you merge and actually also release `v0.10.6` so this trickles down to the projects using paradox? To get those projects aways from using repo.scala-sbt.org... Thanks!
I see since `v0.10.5` there are just version bumps in the `main` branch, so it shouldn't hurt to cut a new release.

**Comment by johanandren** [comment]
0.10.6 release triggered

**Comment by mkurz** [comment]
> 0.10.6 release triggered

https://repo1.maven.org/maven2/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.10.6/sbt-paradox_2.12_1.0-0.10.6.pom

**Pull request merged**
