### PR TITLE
Workarounds for Windows FSs. Fixes #42

### LINKED ISSUE #42: URISyntaxException
I get the following when trying out Paradox on Windows:

```
[error] (akka-docs-new/compile:paradoxMarkdownToHtml) java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\Varga\workspace\akka\akka-docs-new\src\main\paradox\
```

I guess it is the backslashes?

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by 2m** [comment]
It might be worth it to setup https://www.appveyor.com PR validation on Windows.

**Comment by eed3si9n** [comment]
+1 on setting up AppVeyor or someone testing this on Windows box, which ever comes first.

**Comment by eed3si9n** [comment]
@gsechaud Was the fix confirmed on your AppVeyor account? If so I'll merge this to unblock Endre.

**Comment by dwijnand** [comment]
Yes: https://ci.appveyor.com/project/gsechaud/paradox/build/1.0.16

But it would be lovely if we could finish up setting this up - I think @eed3si9n (being an org owner) you just need to hit the buttons in AppVeyor to finish setting this up.

**Comment by eed3si9n** [comment]
@dwijnand I tried but lightbend organization isn't listed on the new project page (I see all other orgs) even though the app seems to be integrated with Github authorization.

**Pull request merged**
