### PR TITLE
feat: migrate to GitHub actions

### PR DESCRIPTION
**Pull request by ennru**
Given the poor handling of the recent security incident (https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/) it is time to get off Travis.

Prior to releasing, secrets need to be added for GitHub actions.

### CODE REVIEW

**Review by pvlugter — APPROVED** [review]
:+1: let's make this switch. Did it run on actions for this PR?

**Comment by pvlugter** [comment]
Removed the Travis required check again.

**Comment by pvlugter** [comment]
Ok, it ran in the fork, but failed: https://github.com/ennru/paradox/actions

Should it be in a branch on this repo so it can run before merging?

**Comment by ennru** [comment]
Superseded by #511

**Pull request closed without merging**
