### PR TITLE
Code snippets now contain a button copying the contents

### PR DESCRIPTION
**Pull request by johanandren**
Two text buttons up top right in snippets now: `[ source ]  [ copy ]`

This aligns the snippets with other doc tools that has a copy button up top right.

### CODE REVIEW

**Comment by ennru** [comment]
The functionality looks good to me.

The design less so (from Paradox own documentation)
image

The scripted test need to be adapted.

**Comment by johanandren** [comment]
Ah, forgot to check the default theme after getting it to work with the akka one indeed. I'll look into the scripted tests as well.

**Comment by johanandren** [comment]
Better now hopefully

Screenshot 2021-02-18 at 16 25 39

**Comment by johanandren** [comment]
Both chrome and firefox messes up the fonts on those buttons though, making them the code font, I'll see if I can fix.

**Review by ennru — APPROVED** [review]
LGTM.

The next request will be to have the "copy" button on all markdown verbatim sections...

**Pull request merged**
