### PR TITLE
Fixes around NPE

### LINKED ISSUE #19: Not setting page.st or a theme results to NPE
### steps

Try using without themes

### problem

```
java.lang.NullPointerException
           at com.lightbend.paradox.template.PageTemplate.write(PageTemplate.scala:35)
           at com.lightbend.paradox.ParadoxProcessor.com$lightbend$paradox$ParadoxProcessor$$render$1(ParadoxProcessor.scala:56)
           at com.lightbend.paradox.ParadoxProcessor$$anonfun$process$1.apply(ParadoxProcessor.scala:60)
           at com.lightbend.paradox.ParadoxProcessor$$anonfun$process$1.apply(ParadoxProcessor.scala:60)
           at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
           at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
           at scala.collection.immutable.List.foreach(List.scala:318)
```

https://github.com/lightbend/paradox/blob/master/core/src/main/scala/com/lightbend/paradox/template/PageTemplate.scala#L35

```
templates.getInstanceOf(name) is null
```

### expectation

Display an error message.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #19 

/review @dwijnand

### CODE REVIEW

**Comment by dwijnand** [comment]
LGTM, clean.

**Comment by dwijnand** [comment]
```
[info] java.lang.RuntimeException: Duplicate mappings:
[info] 	/tmp/sbt_23bd180c/site/target/paradox/site/css/page.css
[info] from
[info] 	/tmp/sbt_23bd180c/site/target/paradox/theme/css/page.css
[info] 		/tmp/sbt_23bd180c/site/src/main/assets/css/page.css
```

**Comment by eed3si9n** [comment]
@dwijnand That's a new one... I'm restarting the Travis job to see if it goes away.

**Comment by eed3si9n** [comment]
The failures are legit. It's because the default value changed for `paradoxTheme`.

**Comment by dwijnand** [comment]
Good to go now.

**Comment by bantonsson** [comment]
👍🏻

**Pull request merged**
