### PR TITLE
Expose page URL to template

### PR DESCRIPTION
**Pull request by raboof**
Might be a first step towards solving #109 more generically

### CODE REVIEW

**Comment by ktoso** [comment]
@pvlugter can we ask for review and release? We'd like to use this for https://github.com/akka/akka-http/issues/1091 and we're focused on getting docs in shape this sprint :)

**Comment by eed3si9n** [comment]
I can get this out now.

**Comment by eed3si9n** [comment]
https://github.com/lightbend/paradox/releases/tag/v0.2.10 is on its way to Maven Central.

**Comment by raboof** [comment]
Thanks!

**Pull request merged**
